services:
  node1:
    build: .
    image: kvick-db
    ports:
      - "5000:5000"
      - "50051:50051"
    environment:
      PORT: 5000
      GRPC_PORT: 50051
      NODE_ID: node1
      SEED_NODES: node1:50051
      ADVERTISE_ADDRESS: node1:50051
      DATA_DIR: /app/data
    volumes:
      - ./data/node1:/app/data
    networks:
      kvick-net:
        aliases:
          - node1

  node2:
    build: .
    image: kvick-db
    ports:
      - "5001:5000"
      - "50052:50051"
    environment:
      PORT: 5000
      GRPC_PORT: 50051
      NODE_ID: node2
      SEED_NODES: node1:50051
      ADVERTISE_ADDRESS: node2:50051
      DATA_DIR: /app/data
    volumes:
      - ./data/node2:/app/data
    depends_on:
      - node1
    networks:
      kvick-net:
        aliases:
          - node2

  node3:
    build: .
    image: kvick-db
    ports:
      - "5002:5000"
      - "50053:50051"
    environment:
      PORT: 5000
      GRPC_PORT: 50051
      NODE_ID: node3
      SEED_NODES: node1:50051
      ADVERTISE_ADDRESS: node3:50051
      DATA_DIR: /app/data
    volumes:
      - ./data/node3:/app/data
    depends_on:
      - node1
    networks:
      kvick-net:
        aliases:
          - node3

networks:
  kvick-net:
    driver: bridge
