services:
  seed:
    image: kvick-db
    build: .
    container_name: kvick-seed
    # Exposing ports for the seed node so the host can send KV client commands to it
    ports: ["8080:8080"]
    volumes: [kvick-seed-data:/app/data]
    environment:
      PORT: 8080
      GRPC_PORT: 50051
      RAFT_PORT: 10051
      SEED_NODES: kvick-seed:50051
      ADVERTISE_ADDRESS: kvick-seed:50051
    networks: [kvick-net]

  worker:
    image: kvick-db
    build: .
    deploy:
      replicas: 4 # You can scale this natively via `docker compose up --scale worker=5`
    environment:
      PORT: 8080
      GRPC_PORT: 50051
      RAFT_PORT: 10051
      # Note: We omit ADVERTISE_ADDRESS and NODE_ID so Dockerfile defaults to $(hostname) dynamically!
      SEED_NODES: kvick-seed:50051
    # We do NOT map ports dynamically to avoid host collision when scaling
    depends_on: [seed]
    networks: [kvick-net]

volumes:
  kvick-seed-data:

networks:
  kvick-net:
    driver: bridge