services:
  node1:
    image: kvick-db
    build: .
    container_name: kvick-node1
    ports: ["8081:8081", "50051:50051", "10051:10051"]
    volumes: [kvick-node1-data:/app/data]
    environment:
      PORT: 8081
      NODE_ID: node1
      GRPC_PORT: 50051
      RAFT_PORT: 10051
      ADVERTISE_ADDRESS: kvick-node1:50051
      SEED_NODES: kvick-node1:50051
    networks: [kvick-net]

  node2:
    image: kvick-db
    build: .
    container_name: kvick-node2
    ports: ["8082:8082", "50052:50052", "10052:10052"]
    volumes: [kvick-node2-data:/app/data]
    environment:
      PORT: 8082
      NODE_ID: node2
      GRPC_PORT: 50052
      RAFT_PORT: 10052
      SEED_NODES: kvick-node1:50051
      ADVERTISE_ADDRESS: kvick-node2:50052
    depends_on: [node1]
    networks: [kvick-net]
volumes:
  kvick-node1-data:
  kvick-node2-data:

networks:
  kvick-net:
    driver: bridge